name = "CorticalParcels"
uuid = "40903625-a1ea-44c8-b7f6-e840be33f0ed"
authors = ["Michael Myers"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
